FROM debian:12-slim
LABEL maintainer "Antti J. Oja <181899832+Yunraze@users.noreply.github.com>"

RUN apt-get update && apt-get install -y \
	automake \
	bison \
	cpp-12 \
	flex \
	gcc-12 \
	gcc \
	gdb \
	libtool \
	make \
	\
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "/bin/bash" ]

